/*
-- Query: SELECT * FROM xjh86w1rt52735sx.links
LIMIT 0, 1000

-- Date: 2018-10-18 15:45
*/
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (1,'https://firebase.google.com/docs/auth/web/start','Get Started with Firebase Authentication on Websites ?|? Firebase','','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (2,'https://unsplash.com/documentation','Unsplash API Documentation | Free HD Photo API | Unsplash','Documentation for the world\'s most powerful free photo API.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (3,'https://www.igdb.com/api','IGDB: Video Game Database API','Video Game database on demand! Images, info video and other data you can retrieve trough the rest API','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (4,'https://unsplash.com/developers','Unsplash Image API | Free HD Photo API','Create with the largest collection of high-quality images that are free to use. Trusted by Trello, Medium, and thousands of other API applications to power their free picture needs.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (5,'https://github.com/abhishekbanthia/Public-APIs','GitHub - abhishekbanthia/Public-APIs: ? A public list of APIs from round the web.','? A public list of APIs from round the web. Contribute to abhishekbanthia/Public-APIs development by creating an account on GitHub.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (6,'https://www.ignitemotion.com/','Free Motion Backgrounds | MP4, MOV video backgrounds for FREE!','Free motion backgrounds, free for commercial or personal use! all videos are High Definition, motion backgrounds to use in your video editing projects.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (7,'https://coverr.co/','Beautiful, free stock video footage for your homepage','Download royalty free (for personal and commercial use), unique and beautiful video footage for your website or any project. No attribution required.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (8,'https://videos.pexels.com/','Free stock videos ? Pexels Videos','Pexels Videos makes it easy to find free stock footage for your website, promo video or anything else. All videos are free for personal and commercial use.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (9,'https://www.pexels.com/','Free stock photos ? Pexels','Free stock photos you can use everywhere. ? Free for commercial use ? No attribution required','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (10,'https://unsplash.com/','Beautiful Free Images & Pictures | Unsplash go to homepage go to collections feed go to search Unsplash Home','Beautiful, free images and photos that you can download and use for any project. Better than any royalty free or stock photos.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (11,'https://pixabay.com/en/','Stunning Free Images ? Pixabay','Discover the best source for free images and videos. Free for commercial use ? No attribution required ?','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (12,'http://brutalistwebsites.com/','Brutalist Websites','','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (13,'https://www.siteinspire.com/','siteInspire - Web Design Inspiration','A CSS gallery and showcase of the best web design inspiration, featuring over 2,500 websites searchable by type, subject, and style.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (14,'https://bestwebsite.gallery/','Best Website Gallery ? Web Design Inspiration ? by @davidhellmann','Welcome to V3.davidhellmann.dev!','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (15,'https://developer.mozilla.org/en-US/docs/Web/API/Geolocation','Geolocation - Web APIs | MDN Github Twitter GitHub Twitter Facebook Instagram','The Geolocation interface represents an object able to programmatically obtain the position of the device. It gives Web content access to the location of the device. This allows a Web site or app to offer customized results based on the user\'s location.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (16,'https://socket.io/','Socket.IO','SOCKET.IO 2.0 IS HERE FEATURING THE FASTEST AND MOST RELIABLE REAL-TIME ENGINE ~/Projects/tweets/index.js var io = require(\'soc','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (17,'http://www.webondevices.com/9-javascript-apis-accessing-device-sensors/#battery-manager-api','9 JavaScript APIs accessing Device Hardware | Web on Devices','My RC car and my desk plant both have an Arduino microcontroller onboard and I used a Node.js server to interface with them through the?','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (18,'https://samiare.github.io/Controller.js/','Controller.js','A library designed to make the Gamepad API easier to use for non-gaming applications.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (19,'https://electronjs.org/','Electron | Build cross platform desktop apps with JavaScript, HTML, and CSS. Electron','','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (20,'https://cordova.apache.org/','Apache Cordova','','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (21,'https://dev.twitch.tv/','Home | Twitch Developers TwitchDevelopers_LogoWhite','Live Streaming, Meet Developers.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (22,'https://materializecss.com/','Documentation - Materialize','Materialize is a modern responsive CSS framework based on Material Design by Google.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (23,'https://foundation.zurb.com/','The most advanced responsive front-end framework in the world. | Foundation','','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (24,'https://getuikit.com/','UIkit','','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (25,'https://minicss.org/','mini.css - Minimal, responsive, style-agnostic CSS framework','mini.css is a tiny CSS framework designed to build quick, modern and responsive websites.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (26,'https://picturepan2.github.io/spectre/index.html','Spectre.css - A Lightweight, Responsive and Modern CSS Framework','','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (27,'https://lipis.github.io/bootstrap-social/','Social Buttons for Bootstrap Fork me on GitHub','','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (28,'https://www.thebestdesigns.com/','The Best Designs - Web Design Inspiration','The best of web design and web design inspiration - updated regularly with new designs and web designers, and featuring the best Wordpress Themes.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (29,'http://unmatchedstyle.com/','Unmatched Style','Our mission is to provide inspiration, motivation and insight into how you design the web.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (30,'http://www.calltoidea.com/','Calltoidea - Light up your imagination','Calltoidea is the unique place where you can find inspiration. A great tool created by a deisnger for web professionals.','',0);
INSERT INTO `links` (`id`,`url`,`title`,`metadata`,`type`,`popularity`) VALUES (31,'https://cssnectar.com/','CSS Gallery for Web Design Inspiration - CSS Nectar','CSS Nectar is a css website design showcase for web designers and developers. Every day we select the best of the web design and add it to our gallery. Submit or suggest a website.','',0);
